FROM python:3.10-slim

WORKDIR /app

# Copy and install Flask dependencies
COPY flask_app/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the Flask application code
COPY flask_app /app

EXPOSE 5000

CMD ["python", "app.py"]
