FROM python:3.10-slim

WORKDIR /app

# Copy and install Django dependencies
COPY django_app/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the entire Django project
COPY django_app /app

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
